apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.app.name}}-virtual-service
  namespace: {{ .Values.namespace.name}}
spec:
  hosts:
  - "squidcorals.sujantechden.uk"
  gateways:
  - istio-system/istio-ingress-gateway
  http:
  - match:
    - uri:
        prefix: /squidcorals

    route:
    - destination:
        host: {{ .Values.app.name}}-service.{{ .Values.namespace.name}}.svc.cluster.local
        port:
          number:  {{ .Values.ports.servicePort}}


