import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './components/NavBar/NavBar'
import NavBar2 from './components/NavBar2/NavBar2'
import BasketProvider from './components/BasketContext/BasketContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body className={inter.className}>

        <header>

        </header>
        <BasketProvider> 
        <NavBar/>
        <NavBar2/>
        {children}
        </BasketProvider>
        <footer></footer>
        </body>
    </html>


  )
}
