app:
  name: squidcorals-frontend
  image:
    name: docker.io/sujan7410/squidcorals-frontend
    tag: dev_test
namespace:
  name: squidcorals-frontend


ports:
  targetPort: 3000
  servicePort: 3000

